[package]
name = "saying_hello_v01"
version = "0.1.0"
authors = ["srodney <stevenrodney@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
